/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package PipneLine.Java;

public class Library {
    public boolean someLibraryMethod() {
      System.out.println("fjshdji1231231231asdasdsad ");

        return true;
    }
}
