/*
 * This Java source file was generated by the Gradxxxxxxxxxxxxxxzzzzzzczzxczxczcle 'init' task.
 */
package PipneLine.Java;

public class Library {
    public boolean someLibraryMethod() {
      System.out.println("fjshdjiasd123213123123iasgdisahdjksadnalsdasdasdsad ");

        return true;
    }
}
