/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package PipneLine.Java;

public class Library {
    public boolean someLibraryMethod() {
      System.out.println("fueaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaatyre 4 ");
        return true;
    }
}
